name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kupono/free-stuff-bot:$GITHUB_RUN_ID --tag kupono/free-stuff-bot:latest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push versioned image to Docker Hub
      run: docker push kupono/free-stuff-bot:$GITHUB_RUN_ID
      
    - name: Push latest image to Docker Hub
      run: docker push kupono/free-stuff-bot:latest
      
